# Generated by Django 2.2.28 on 2023-06-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=158)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSectorDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUST_ID', models.CharField(max_length=255)),
                ('LOCATION', models.CharField(max_length=255)),
                ('SECTOR_ADJ', models.CharField(max_length=255)),
                ('OBLIGOR_RISK_RATING', models.FloatField(null=True)),
                ('IFRS_CLASSIFICATION', models.CharField(db_column='IFRS_ CLASSIFICATION', max_length=255)),
                ('SBU_DIVISION', models.CharField(max_length=255)),
                ('CBK_GRADE', models.FloatField(db_column='CBK GRADE', null=True)),
            ],
            options={
                'db_table': 'stg_customer_sector_details',
            },
        ),
        migrations.CreateModel(
            name='LimitDefinition',
            fields=[
                ('Name', models.CharField(max_length=255, null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Category', models.CharField(max_length=255, null=True)),
                ('Limit', models.CharField(max_length=255, null=True)),
                ('ThresholdTarget', models.CharField(max_length=255, null=True)),
                ('ordernumber', models.BigIntegerField(null=True)),
                ('subCategory', models.CharField(max_length=50, null=True)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryCode', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'Limit_Definition_',
            },
        ),
    ]
