# Generated by Django 2.2.28 on 2023-06-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customersectordetails',
            old_name='SECTOR_ADJ',
            new_name='SECTOR_DESC',
        ),
        migrations.AddField(
            model_name='customersectordetails',
            name='SECTOR_CODE',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
