# Generated by Django 2.2.28 on 2023-06-12 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230612_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clr',
            old_name='sn',
            new_name='s_n',
        ),
    ]
