# Generated by Django 2.2.28 on 2023-06-12 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230612_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clr',
            old_name='s_n',
            new_name='sn',
        ),
    ]
