# Generated by Django 2.2.28 on 2023-06-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230612_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clr',
            old_name='collateral_status',
            new_name='COLLATERAL_STATUS',
        ),
        migrations.RenameField(
            model_name='clr',
            old_name='currency_short_name',
            new_name='CURRENCY_SHORT_NAME',
        ),
        migrations.RenameField(
            model_name='clr',
            old_name='currency_type',
            new_name='CURRENCY_TYPE',
        ),
        migrations.RenameField(
            model_name='clr',
            old_name='current_valuation_date',
            new_name='CURRENT_VALUATION_DATE',
        ),
        migrations.RenameField(
            model_name='clr',
            old_name='cust_id',
            new_name='CUST_ID',
        ),
        migrations.RenameField(
            model_name='clr',
            old_name='cust_id1',
            new_name='CUST_ID1',
        ),
        migrations.RenameField(
            model_name='clr',
            old_name='exposure_type',
            new_name='EXPOSURE_TYPE',
        ),
        migrations.RenameField(
            model_name='clr',
            old_name='facility_description',
            new_name='FACILITY_DESCRIPTION',
        ),
        migrations.RenameField(
            model_name='clr',
            old_name='facility_type',
            new_name='FACILITY_TYPE',
        ),
        migrations.RenameField(
            model_name='clr',
            old_name='fx_rate',
            new_name='FX_RATE',
        ),
        migrations.RenameField(
            model_name='clr',
            old_name='group_name',
            new_name='GROUP_NAME',
        ),
        migrations.RenameField(
            model_name='clr',
            old_name='group_name1',
            new_name='GROUP_NAME1',
        ),
        migrations.RenameField(
            model_name='clr',
            old_name='ifrs_classification',
            new_name='IFRS_CLASSIFICATION',
        ),
        migrations.RenameField(
            model_name='clr',
            old_name='location',
            new_name='LOCATION',
        ),
        migrations.RenameField(
            model_name='clr',
            old_name='maturity_date',
            new_name='MATURITY_DATE',
        ),
        migrations.RenameField(
            model_name='clr',
            old_name='obligor_risk_rating',
            new_name='OBLIGOR_RISK_RATING',
        ),
        migrations.RenameField(
            model_name='clr',
            old_name='product',
            new_name='PRODUCT',
        ),
        migrations.RenameField(
            model_name='clr',
            old_name='prudential_classification',
            new_name='PRUDENTIAL_CLASSIFICATION',
        ),
    ]
