# Generated by Django 2.2.28 on 2023-06-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20230612_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clr',
            name='AGE_OF_UNPAID_OBLIGATION_DAYS',
            field=models.FloatField(db_column='AGE_OF_UNPAID_OBLIGATION_DAYS', null=True),
        ),
        migrations.AlterField(
            model_name='clr',
            name='APPROVED_AMOUNT_ORIGINAL_CCY',
            field=models.FloatField(db_column='APPROVED_AMOUNT_ORIGINAL_CCY', null=True),
        ),
        migrations.AlterField(
            model_name='clr',
            name='APPROVED_AMOUNT_USD',
            field=models.FloatField(db_column='APPROVED_AMOUNT_USD', null=True),
        ),
        migrations.AlterField(
            model_name='clr',
            name='BUSINESS_UNIT_DIVISION',
            field=models.CharField(db_column='BUSINESS_UNIT_DIVISION', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clr',
            name='CAP_ERA_INTEREST_RATES',
            field=models.CharField(db_column='CAP_ERA_INTEREST_RATES', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clr',
            name='CBK_GRADE',
            field=models.FloatField(db_column='CBK_GRADE', null=True),
        ),
        migrations.AlterField(
            model_name='clr',
            name='COLLATERAL_VALUE_KES',
            field=models.FloatField(db_column='COLLATERAL_VALUE_KES', null=True),
        ),
        migrations.AlterField(
            model_name='clr',
            name='COLLATERAL_VALUE_USD',
            field=models.CharField(db_column='COLLATERAL_VALUE_USD', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clr',
            name='CURRENT_EXPOSURE_ORIGINAL_CCY',
            field=models.FloatField(db_column='CURRENT_EXPOSURE_ORIGINAL_CCY', null=True),
        ),
        migrations.AlterField(
            model_name='clr',
            name='CURRENT_EXPOSURE_USD',
            field=models.FloatField(db_column='CURRENT_EXPOSURE_USD', null=True),
        ),
        migrations.AlterField(
            model_name='clr',
            name='DATE_OF_LAST_CREDIT',
            field=models.DateTimeField(db_column='DATE_OF_LAST_CREDIT', null=True),
        ),
        migrations.AlterField(
            model_name='clr',
            name='IMPAIRMENT_USD',
            field=models.FloatField(db_column='IMPAIRMENT_USD', null=True),
        ),
        migrations.AlterField(
            model_name='clr',
            name='LAST_CREDIT_AMOUNT',
            field=models.FloatField(db_column='LAST_CREDIT_AMOUNT', null=True),
        ),
        migrations.AlterField(
            model_name='clr',
            name='ONE_MONTH_COLLECTION',
            field=models.FloatField(db_column='1_MONTH_COLLECTION', null=True),
        ),
        migrations.AlterField(
            model_name='clr',
            name='OUTSTANDING_BALANCE_USD',
            field=models.FloatField(db_column='OUTSTANDING_BALANCE_USD', null=True),
        ),
        migrations.AlterField(
            model_name='clr',
            name='S_N',
            field=models.FloatField(db_column='S_N', null=True),
        ),
        migrations.AlterField(
            model_name='clr',
            name='THREE_MONTHS_COLLECTIONS',
            field=models.CharField(db_column='3_MONTHS_COLLECTIONS', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clr',
            name='UNPAID_AMOUNT_GHC_MISSED',
            field=models.FloatField(db_column='UNPAID_AMOUNT_GHC_MISSED', null=True),
        ),
        migrations.AlterField(
            model_name='clr',
            name='UNPAID_AMOUNT_USD',
            field=models.FloatField(db_column='UNPAID_AMOUNT_USD', null=True),
        ),
    ]
