# Generated by Django 2.2.28 on 2023-06-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20230612_1458'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CLR',
            new_name='CLRNew',
        ),
    ]
