# Generated by Django 2.2.28 on 2023-06-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20230612_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSectorDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUST_ID', models.CharField(max_length=255)),
                ('LOCATION', models.CharField(max_length=255)),
                ('SECTOR_ADJ', models.CharField(max_length=255)),
                ('OBLIGOR_RISK_RATING', models.FloatField(null=True)),
                ('IFRS_CLASSIFICATION', models.CharField(max_length=255)),
                ('SBU_DIVISION', models.CharField(max_length=255)),
                ('CBK_GRADE', models.FloatField(db_column='CBK GRADE', null=True)),
            ],
            options={
                'db_table': 'stg_customer_sector_details',
            },
        ),
    ]
