# Generated by Django 2.2.28 on 2023-06-22 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_customersectordetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewCLR',
        ),
    ]
